insert into product values(1000,'GEN 4 SMARTWATCH','GEN 4 SMARTWATCH - VENTURE HR ROSE GOLD-TONE STAINLESS STEEL INTERCHANGEABLE STRAP BOX SET','FTW6021SETP','350.00');
insert into product values(1001,'HYBRID SMARTWATCH','HYBRID SMARTWATCH - HARPER ROSE GOLD-TONE STAINLESS STEEL','FTW5028P','115.00');
insert into product values(1002,'PRESLEY THREE','PRESLEY THREE-HAND BLUSH LEATHER WATCH','ES4600P','85.00');
insert into product values(1003,'CARLIE MINI THREE','CARLIE MINI THREE-HAND BLACK LEATHER WATCH AND BRACELET BOX SET','ES4506SETP','135.00');
insert into product values(1004,'CARLIE CARBON SERIES THREE','CARLIE CARBON SERIES THREE-HAND BLACK STAINLESS STEEL WATCH','ES4442P','135.00');